FROM python:latest AS base

RUN pip install flask
RUN pip install redis
RUN pip install requests
RUN pip install flask_cors

# COPY from DB-Manager
COPY . /app 

WORKDIR /app

RUN chmod +x run.sh
EXPOSE 3001

ENV ai_engine_domain $ai_engine_domain
ENV redis_domain $redis_domain

ENTRYPOINT [ "sh", "run.sh" ]