FROM python:latest AS base

RUN pip install flask
RUN pip install requests

# COPY from AI-Engine
COPY . /app 

WORKDIR /app

RUN chmod +x ./run.sh
EXPOSE 3002

ENV db_manager_domain $db_manager_domain

ENTRYPOINT [ "sh", "run.sh" ]