# python镜像
FROM python:3.8-slim

# 工作目录
WORKDIR /app

# 将当前目录内容复制到位于/app中的容器中
COPY . /app

# 安装requirements.txt中指定的任何所需包
RUN pip install --no-cache-dir -r requirements.txt

# duankou
EXPOSE 5000

# 定义变量
ENV NAME World

# 运行app.py
CMD ["python", "app.py"]

