version: '3.8'

services:
  ai-engine:
    build:
      context: ../AI-Engine
      dockerfile: ../Docker/Dockerfile.ai-engine
    ports:
      - "3002:3002"
    command: --host=0.0.0.0
    container_name: ai-engine-test
    image: ai-engine
    environment:
      - db_manager_domain=db-manager

  db-manager:
    build:
      context: ../DB-Manager
      dockerfile: ../Docker/Dockerfile.db-manager
    ports:
      - "3001:3001"
    command: --host=0.0.0.0
    container_name: db-manager-test
    image: db-manager
    environment:
      - ai_engine_domain=ai-engine
      - redis_domain=redis


  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "3003:8001"
    container_name: redis-test

  frontend:
    build:
      context: ../Frontend
      dockerfile: ../Docker/Dockerfile.frontend
    ports:
      # - "3000:3000"
      - "80:3000"
    command: --host=0.0.0.0
    container_name: frontend-test
    image: frontend
